name: gen-html

permissions:
  contents: write

on:
  workflow_dispatch: {}
  schedule:
    # runs twice daily, at 01:00 UTC and 13:00 UTC
    - cron: '0 1 * * *'
    - cron: '0 13 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for gitsign auth
      contents: write # Needed to commit files back to repo
    steps:
      - name: checkout repo content
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.2
      - uses: imjasonh/setup-crane@00c9e93efa4e1138c9a7a5c594acd6c75a2fbf0c # v0.3
      - name: setup python
        uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
        with:
          python-version: '3.12'
      - name: execute shell script
        id: run
        run: |
          ./gen-html.sh
      - uses: stefanzweifel/git-auto-commit-action@v5
